### ISSUE TITLE
Instructions to open Selenium IDE in newest Firefox version

### ISSUE THREAD

**Issue by packapotatoes** [LaboonCourses/CS1632_Summer#4]
Right click the top bar of firefox, between the open tabs and the minimize button. Click "Menu Bar" so the menu bar shows up in the top left corner. Under "Tools" is "Selenium IDE".

Alternatively, "ctrl+alt+s" while in the Firefox window should bring up the IDE

**Comment by laboon** [comment]
Thanks, please write "+5 Issue 4" on your submission sheet for 5 bonus points on Deliverable 3.

**Comment by laboon** [comment]
Points added, thank you
